### ISSUE TITLE
Add ability to import via docker image

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/seed-images#3]
If your image hasn't been scanned by silo yet, it would be useful to add the ability to pull the manifest from an image by giving the docker image URL. 

- Add a button on the images panel to import an image via Docker URL
- Call silo/images/manifest/docker_url to pull the manifest from the seed image
- Continue as normal

**Comment by cshamis** [comment]
My $.02

1) SILO + SEEDVAULT are an inseparable part of SCALE now.
2) Like it or not, SEEDVAULT has become the "app-store" of possible SCALE
jobs.
3) SILO/SEEDVAULT exist for the singular purpose of adding jobs into SCALE.

For starters, let's just add a command line in seed-cli to publish a SEED
manifest directly to a SCALE/SILO instance and display a text
status-message from the SILO.

This is why I think it's the right approach:

a) it directly addresses the pain point of eliminating the scraping delay.
b) it's understandable to the users what is going on.  Publish to REPO-A,
notify SILO-B.  Can now run in SCALE-C
c) it's not a lot of code for us.

Risks:
i) DoS on the SILO?
ii) Poisoning the SILO?
iii) if it doesn't work, we discontinue the command line option, and can
put in the status-message explaining how it's discontinued and the new
method to accomplish.

I think these risks can be mitigated with authentication.  Since SILO is a
part of SCALE, this means SILO and SCALE can share IdAM solutions.

Discuss?

**Comment by gisjedi** [comment]
Silo issue to accept notification of updates: https://github.com/ngageoint/seed-silo/issues/31
Seed issue for publish to Silo: https://github.com/ngageoint/seed-cli/issues/226
